/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PaywallPreviewRouteImport } from './routes/paywall-preview'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DevRitualRouteImport } from './routes/dev-ritual'
import { Route as BadgePreviewRouteImport } from './routes/badge-preview'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JoinGroupIdRouteImport } from './routes/join.$groupId'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPlanRouteImport } from './routes/_authenticated/plan'
import { Route as AuthenticatedNewPactaraRouteImport } from './routes/_authenticated/new-pactara'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedGroupsRouteImport } from './routes/_authenticated/groups'
import { Route as DotwellKnownAppleAppSiteAssociationRouteImport } from './routes/[.]well-known/apple-app-site-association'
import { Route as AuthenticatedCheckInIndexRouteImport } from './routes/_authenticated/check-in.index'
import { Route as AuthenticatedChatIndexRouteImport } from './routes/_authenticated/chat.index'
import { Route as AuthenticatedAccountSettingsIndexRouteImport } from './routes/_authenticated/account-settings.index'
import { Route as AuthenticatedCheckInNotesRouteImport } from './routes/_authenticated/check-in.notes'
import { Route as AuthenticatedCheckInCameraRouteImport } from './routes/_authenticated/check-in.camera'
import { Route as AuthenticatedChatGroupIdRouteImport } from './routes/_authenticated/chat.$groupId'
import { Route as AuthenticatedAccountSettingsPasswordRouteImport } from './routes/_authenticated/account-settings.password'
import { Route as AuthenticatedAccountSettingsNotificationsRouteImport } from './routes/_authenticated/account-settings.notifications'
import { Route as AuthenticatedAccountSettingsNameRouteImport } from './routes/_authenticated/account-settings.name'
import { Route as AuthenticatedAccountSettingsEmailRouteImport } from './routes/_authenticated/account-settings.email'
import { Route as ApiPublicHooksMorningRitualReminderRouteImport } from './routes/api/public/hooks/morning-ritual-reminder'
import { Route as ApiPublicHooksDailyReminderRouteImport } from './routes/api/public/hooks/daily-reminder'
import { Route as ApiPublicHooksAutoMissRouteImport } from './routes/api/public/hooks/auto-miss'
import { Route as ApiPublicOgInviteGroupIdRouteImport } from './routes/api/public/og/invite/$groupId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PaywallPreviewRoute = PaywallPreviewRouteImport.update({
  id: '/paywall-preview',
  path: '/paywall-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DevRitualRoute = DevRitualRouteImport.update({
  id: '/dev-ritual',
  path: '/dev-ritual',
  getParentRoute: () => rootRouteImport,
} as any)
const BadgePreviewRoute = BadgePreviewRouteImport.update({
  id: '/badge-preview',
  path: '/badge-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinGroupIdRoute = JoinGroupIdRouteImport.update({
  id: '/join/$groupId',
  path: '/join/$groupId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlanRoute = AuthenticatedPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNewPactaraRoute = AuthenticatedNewPactaraRouteImport.update({
  id: '/new-pactara',
  path: '/new-pactara',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGroupsRoute = AuthenticatedGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const DotwellKnownAppleAppSiteAssociationRoute =
  DotwellKnownAppleAppSiteAssociationRouteImport.update({
    id: '/.well-known/apple-app-site-association',
    path: '/.well-known/apple-app-site-association',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedCheckInIndexRoute =
  AuthenticatedCheckInIndexRouteImport.update({
    id: '/check-in/',
    path: '/check-in/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatIndexRoute = AuthenticatedChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountSettingsIndexRoute =
  AuthenticatedAccountSettingsIndexRouteImport.update({
    id: '/account-settings/',
    path: '/account-settings/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCheckInNotesRoute =
  AuthenticatedCheckInNotesRouteImport.update({
    id: '/check-in/notes',
    path: '/check-in/notes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCheckInCameraRoute =
  AuthenticatedCheckInCameraRouteImport.update({
    id: '/check-in/camera',
    path: '/check-in/camera',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatGroupIdRoute =
  AuthenticatedChatGroupIdRouteImport.update({
    id: '/chat/$groupId',
    path: '/chat/$groupId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccountSettingsPasswordRoute =
  AuthenticatedAccountSettingsPasswordRouteImport.update({
    id: '/account-settings/password',
    path: '/account-settings/password',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccountSettingsNotificationsRoute =
  AuthenticatedAccountSettingsNotificationsRouteImport.update({
    id: '/account-settings/notifications',
    path: '/account-settings/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccountSettingsNameRoute =
  AuthenticatedAccountSettingsNameRouteImport.update({
    id: '/account-settings/name',
    path: '/account-settings/name',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccountSettingsEmailRoute =
  AuthenticatedAccountSettingsEmailRouteImport.update({
    id: '/account-settings/email',
    path: '/account-settings/email',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicHooksMorningRitualReminderRoute =
  ApiPublicHooksMorningRitualReminderRouteImport.update({
    id: '/api/public/hooks/morning-ritual-reminder',
    path: '/api/public/hooks/morning-ritual-reminder',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDailyReminderRoute =
  ApiPublicHooksDailyReminderRouteImport.update({
    id: '/api/public/hooks/daily-reminder',
    path: '/api/public/hooks/daily-reminder',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksAutoMissRoute = ApiPublicHooksAutoMissRouteImport.update({
  id: '/api/public/hooks/auto-miss',
  path: '/api/public/hooks/auto-miss',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOgInviteGroupIdRoute =
  ApiPublicOgInviteGroupIdRouteImport.update({
    id: '/api/public/og/invite/$groupId',
    path: '/api/public/og/invite/$groupId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/badge-preview': typeof BadgePreviewRoute
  '/dev-ritual': typeof DevRitualRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/paywall-preview': typeof PaywallPreviewRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/.well-known/apple-app-site-association': typeof DotwellKnownAppleAppSiteAssociationRoute
  '/groups': typeof AuthenticatedGroupsRoute
  '/home': typeof AuthenticatedHomeRoute
  '/new-pactara': typeof AuthenticatedNewPactaraRoute
  '/plan': typeof AuthenticatedPlanRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/join/$groupId': typeof JoinGroupIdRoute
  '/account-settings/email': typeof AuthenticatedAccountSettingsEmailRoute
  '/account-settings/name': typeof AuthenticatedAccountSettingsNameRoute
  '/account-settings/notifications': typeof AuthenticatedAccountSettingsNotificationsRoute
  '/account-settings/password': typeof AuthenticatedAccountSettingsPasswordRoute
  '/chat/$groupId': typeof AuthenticatedChatGroupIdRoute
  '/check-in/camera': typeof AuthenticatedCheckInCameraRoute
  '/check-in/notes': typeof AuthenticatedCheckInNotesRoute
  '/account-settings/': typeof AuthenticatedAccountSettingsIndexRoute
  '/chat/': typeof AuthenticatedChatIndexRoute
  '/check-in/': typeof AuthenticatedCheckInIndexRoute
  '/api/public/hooks/auto-miss': typeof ApiPublicHooksAutoMissRoute
  '/api/public/hooks/daily-reminder': typeof ApiPublicHooksDailyReminderRoute
  '/api/public/hooks/morning-ritual-reminder': typeof ApiPublicHooksMorningRitualReminderRoute
  '/api/public/og/invite/$groupId': typeof ApiPublicOgInviteGroupIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/badge-preview': typeof BadgePreviewRoute
  '/dev-ritual': typeof DevRitualRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/paywall-preview': typeof PaywallPreviewRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/.well-known/apple-app-site-association': typeof DotwellKnownAppleAppSiteAssociationRoute
  '/groups': typeof AuthenticatedGroupsRoute
  '/home': typeof AuthenticatedHomeRoute
  '/new-pactara': typeof AuthenticatedNewPactaraRoute
  '/plan': typeof AuthenticatedPlanRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/join/$groupId': typeof JoinGroupIdRoute
  '/account-settings/email': typeof AuthenticatedAccountSettingsEmailRoute
  '/account-settings/name': typeof AuthenticatedAccountSettingsNameRoute
  '/account-settings/notifications': typeof AuthenticatedAccountSettingsNotificationsRoute
  '/account-settings/password': typeof AuthenticatedAccountSettingsPasswordRoute
  '/chat/$groupId': typeof AuthenticatedChatGroupIdRoute
  '/check-in/camera': typeof AuthenticatedCheckInCameraRoute
  '/check-in/notes': typeof AuthenticatedCheckInNotesRoute
  '/account-settings': typeof AuthenticatedAccountSettingsIndexRoute
  '/chat': typeof AuthenticatedChatIndexRoute
  '/check-in': typeof AuthenticatedCheckInIndexRoute
  '/api/public/hooks/auto-miss': typeof ApiPublicHooksAutoMissRoute
  '/api/public/hooks/daily-reminder': typeof ApiPublicHooksDailyReminderRoute
  '/api/public/hooks/morning-ritual-reminder': typeof ApiPublicHooksMorningRitualReminderRoute
  '/api/public/og/invite/$groupId': typeof ApiPublicOgInviteGroupIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/badge-preview': typeof BadgePreviewRoute
  '/dev-ritual': typeof DevRitualRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/paywall-preview': typeof PaywallPreviewRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/.well-known/apple-app-site-association': typeof DotwellKnownAppleAppSiteAssociationRoute
  '/_authenticated/groups': typeof AuthenticatedGroupsRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/new-pactara': typeof AuthenticatedNewPactaraRoute
  '/_authenticated/plan': typeof AuthenticatedPlanRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/join/$groupId': typeof JoinGroupIdRoute
  '/_authenticated/account-settings/email': typeof AuthenticatedAccountSettingsEmailRoute
  '/_authenticated/account-settings/name': typeof AuthenticatedAccountSettingsNameRoute
  '/_authenticated/account-settings/notifications': typeof AuthenticatedAccountSettingsNotificationsRoute
  '/_authenticated/account-settings/password': typeof AuthenticatedAccountSettingsPasswordRoute
  '/_authenticated/chat/$groupId': typeof AuthenticatedChatGroupIdRoute
  '/_authenticated/check-in/camera': typeof AuthenticatedCheckInCameraRoute
  '/_authenticated/check-in/notes': typeof AuthenticatedCheckInNotesRoute
  '/_authenticated/account-settings/': typeof AuthenticatedAccountSettingsIndexRoute
  '/_authenticated/chat/': typeof AuthenticatedChatIndexRoute
  '/_authenticated/check-in/': typeof AuthenticatedCheckInIndexRoute
  '/api/public/hooks/auto-miss': typeof ApiPublicHooksAutoMissRoute
  '/api/public/hooks/daily-reminder': typeof ApiPublicHooksDailyReminderRoute
  '/api/public/hooks/morning-ritual-reminder': typeof ApiPublicHooksMorningRitualReminderRoute
  '/api/public/og/invite/$groupId': typeof ApiPublicOgInviteGroupIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/badge-preview'
    | '/dev-ritual'
    | '/forgot-password'
    | '/login'
    | '/paywall-preview'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/support'
    | '/terms'
    | '/.well-known/apple-app-site-association'
    | '/groups'
    | '/home'
    | '/new-pactara'
    | '/plan'
    | '/profile'
    | '/join/$groupId'
    | '/account-settings/email'
    | '/account-settings/name'
    | '/account-settings/notifications'
    | '/account-settings/password'
    | '/chat/$groupId'
    | '/check-in/camera'
    | '/check-in/notes'
    | '/account-settings/'
    | '/chat/'
    | '/check-in/'
    | '/api/public/hooks/auto-miss'
    | '/api/public/hooks/daily-reminder'
    | '/api/public/hooks/morning-ritual-reminder'
    | '/api/public/og/invite/$groupId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/badge-preview'
    | '/dev-ritual'
    | '/forgot-password'
    | '/login'
    | '/paywall-preview'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/support'
    | '/terms'
    | '/.well-known/apple-app-site-association'
    | '/groups'
    | '/home'
    | '/new-pactara'
    | '/plan'
    | '/profile'
    | '/join/$groupId'
    | '/account-settings/email'
    | '/account-settings/name'
    | '/account-settings/notifications'
    | '/account-settings/password'
    | '/chat/$groupId'
    | '/check-in/camera'
    | '/check-in/notes'
    | '/account-settings'
    | '/chat'
    | '/check-in'
    | '/api/public/hooks/auto-miss'
    | '/api/public/hooks/daily-reminder'
    | '/api/public/hooks/morning-ritual-reminder'
    | '/api/public/og/invite/$groupId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/badge-preview'
    | '/dev-ritual'
    | '/forgot-password'
    | '/login'
    | '/paywall-preview'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/support'
    | '/terms'
    | '/.well-known/apple-app-site-association'
    | '/_authenticated/groups'
    | '/_authenticated/home'
    | '/_authenticated/new-pactara'
    | '/_authenticated/plan'
    | '/_authenticated/profile'
    | '/join/$groupId'
    | '/_authenticated/account-settings/email'
    | '/_authenticated/account-settings/name'
    | '/_authenticated/account-settings/notifications'
    | '/_authenticated/account-settings/password'
    | '/_authenticated/chat/$groupId'
    | '/_authenticated/check-in/camera'
    | '/_authenticated/check-in/notes'
    | '/_authenticated/account-settings/'
    | '/_authenticated/chat/'
    | '/_authenticated/check-in/'
    | '/api/public/hooks/auto-miss'
    | '/api/public/hooks/daily-reminder'
    | '/api/public/hooks/morning-ritual-reminder'
    | '/api/public/og/invite/$groupId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  BadgePreviewRoute: typeof BadgePreviewRoute
  DevRitualRoute: typeof DevRitualRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PaywallPreviewRoute: typeof PaywallPreviewRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
  DotwellKnownAppleAppSiteAssociationRoute: typeof DotwellKnownAppleAppSiteAssociationRoute
  JoinGroupIdRoute: typeof JoinGroupIdRoute
  ApiPublicHooksAutoMissRoute: typeof ApiPublicHooksAutoMissRoute
  ApiPublicHooksDailyReminderRoute: typeof ApiPublicHooksDailyReminderRoute
  ApiPublicHooksMorningRitualReminderRoute: typeof ApiPublicHooksMorningRitualReminderRoute
  ApiPublicOgInviteGroupIdRoute: typeof ApiPublicOgInviteGroupIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paywall-preview': {
      id: '/paywall-preview'
      path: '/paywall-preview'
      fullPath: '/paywall-preview'
      preLoaderRoute: typeof PaywallPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev-ritual': {
      id: '/dev-ritual'
      path: '/dev-ritual'
      fullPath: '/dev-ritual'
      preLoaderRoute: typeof DevRitualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/badge-preview': {
      id: '/badge-preview'
      path: '/badge-preview'
      fullPath: '/badge-preview'
      preLoaderRoute: typeof BadgePreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$groupId': {
      id: '/join/$groupId'
      path: '/join/$groupId'
      fullPath: '/join/$groupId'
      preLoaderRoute: typeof JoinGroupIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plan': {
      id: '/_authenticated/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof AuthenticatedPlanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/new-pactara': {
      id: '/_authenticated/new-pactara'
      path: '/new-pactara'
      fullPath: '/new-pactara'
      preLoaderRoute: typeof AuthenticatedNewPactaraRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/groups': {
      id: '/_authenticated/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof AuthenticatedGroupsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.well-known/apple-app-site-association': {
      id: '/.well-known/apple-app-site-association'
      path: '/.well-known/apple-app-site-association'
      fullPath: '/.well-known/apple-app-site-association'
      preLoaderRoute: typeof DotwellKnownAppleAppSiteAssociationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/check-in/': {
      id: '/_authenticated/check-in/'
      path: '/check-in'
      fullPath: '/check-in/'
      preLoaderRoute: typeof AuthenticatedCheckInIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat/': {
      id: '/_authenticated/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof AuthenticatedChatIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account-settings/': {
      id: '/_authenticated/account-settings/'
      path: '/account-settings'
      fullPath: '/account-settings/'
      preLoaderRoute: typeof AuthenticatedAccountSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/check-in/notes': {
      id: '/_authenticated/check-in/notes'
      path: '/check-in/notes'
      fullPath: '/check-in/notes'
      preLoaderRoute: typeof AuthenticatedCheckInNotesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/check-in/camera': {
      id: '/_authenticated/check-in/camera'
      path: '/check-in/camera'
      fullPath: '/check-in/camera'
      preLoaderRoute: typeof AuthenticatedCheckInCameraRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat/$groupId': {
      id: '/_authenticated/chat/$groupId'
      path: '/chat/$groupId'
      fullPath: '/chat/$groupId'
      preLoaderRoute: typeof AuthenticatedChatGroupIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account-settings/password': {
      id: '/_authenticated/account-settings/password'
      path: '/account-settings/password'
      fullPath: '/account-settings/password'
      preLoaderRoute: typeof AuthenticatedAccountSettingsPasswordRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account-settings/notifications': {
      id: '/_authenticated/account-settings/notifications'
      path: '/account-settings/notifications'
      fullPath: '/account-settings/notifications'
      preLoaderRoute: typeof AuthenticatedAccountSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account-settings/name': {
      id: '/_authenticated/account-settings/name'
      path: '/account-settings/name'
      fullPath: '/account-settings/name'
      preLoaderRoute: typeof AuthenticatedAccountSettingsNameRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account-settings/email': {
      id: '/_authenticated/account-settings/email'
      path: '/account-settings/email'
      fullPath: '/account-settings/email'
      preLoaderRoute: typeof AuthenticatedAccountSettingsEmailRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/hooks/morning-ritual-reminder': {
      id: '/api/public/hooks/morning-ritual-reminder'
      path: '/api/public/hooks/morning-ritual-reminder'
      fullPath: '/api/public/hooks/morning-ritual-reminder'
      preLoaderRoute: typeof ApiPublicHooksMorningRitualReminderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/daily-reminder': {
      id: '/api/public/hooks/daily-reminder'
      path: '/api/public/hooks/daily-reminder'
      fullPath: '/api/public/hooks/daily-reminder'
      preLoaderRoute: typeof ApiPublicHooksDailyReminderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/auto-miss': {
      id: '/api/public/hooks/auto-miss'
      path: '/api/public/hooks/auto-miss'
      fullPath: '/api/public/hooks/auto-miss'
      preLoaderRoute: typeof ApiPublicHooksAutoMissRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/og/invite/$groupId': {
      id: '/api/public/og/invite/$groupId'
      path: '/api/public/og/invite/$groupId'
      fullPath: '/api/public/og/invite/$groupId'
      preLoaderRoute: typeof ApiPublicOgInviteGroupIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedGroupsRoute: typeof AuthenticatedGroupsRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedNewPactaraRoute: typeof AuthenticatedNewPactaraRoute
  AuthenticatedPlanRoute: typeof AuthenticatedPlanRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedAccountSettingsEmailRoute: typeof AuthenticatedAccountSettingsEmailRoute
  AuthenticatedAccountSettingsNameRoute: typeof AuthenticatedAccountSettingsNameRoute
  AuthenticatedAccountSettingsNotificationsRoute: typeof AuthenticatedAccountSettingsNotificationsRoute
  AuthenticatedAccountSettingsPasswordRoute: typeof AuthenticatedAccountSettingsPasswordRoute
  AuthenticatedChatGroupIdRoute: typeof AuthenticatedChatGroupIdRoute
  AuthenticatedCheckInCameraRoute: typeof AuthenticatedCheckInCameraRoute
  AuthenticatedCheckInNotesRoute: typeof AuthenticatedCheckInNotesRoute
  AuthenticatedAccountSettingsIndexRoute: typeof AuthenticatedAccountSettingsIndexRoute
  AuthenticatedChatIndexRoute: typeof AuthenticatedChatIndexRoute
  AuthenticatedCheckInIndexRoute: typeof AuthenticatedCheckInIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedGroupsRoute: AuthenticatedGroupsRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedNewPactaraRoute: AuthenticatedNewPactaraRoute,
  AuthenticatedPlanRoute: AuthenticatedPlanRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedAccountSettingsEmailRoute:
    AuthenticatedAccountSettingsEmailRoute,
  AuthenticatedAccountSettingsNameRoute: AuthenticatedAccountSettingsNameRoute,
  AuthenticatedAccountSettingsNotificationsRoute:
    AuthenticatedAccountSettingsNotificationsRoute,
  AuthenticatedAccountSettingsPasswordRoute:
    AuthenticatedAccountSettingsPasswordRoute,
  AuthenticatedChatGroupIdRoute: AuthenticatedChatGroupIdRoute,
  AuthenticatedCheckInCameraRoute: AuthenticatedCheckInCameraRoute,
  AuthenticatedCheckInNotesRoute: AuthenticatedCheckInNotesRoute,
  AuthenticatedAccountSettingsIndexRoute:
    AuthenticatedAccountSettingsIndexRoute,
  AuthenticatedChatIndexRoute: AuthenticatedChatIndexRoute,
  AuthenticatedCheckInIndexRoute: AuthenticatedCheckInIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  BadgePreviewRoute: BadgePreviewRoute,
  DevRitualRoute: DevRitualRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PaywallPreviewRoute: PaywallPreviewRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
  DotwellKnownAppleAppSiteAssociationRoute:
    DotwellKnownAppleAppSiteAssociationRoute,
  JoinGroupIdRoute: JoinGroupIdRoute,
  ApiPublicHooksAutoMissRoute: ApiPublicHooksAutoMissRoute,
  ApiPublicHooksDailyReminderRoute: ApiPublicHooksDailyReminderRoute,
  ApiPublicHooksMorningRitualReminderRoute:
    ApiPublicHooksMorningRitualReminderRoute,
  ApiPublicOgInviteGroupIdRoute: ApiPublicOgInviteGroupIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
