/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedInviteRouteImport } from './routes/_authenticated/invite'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedGroupsRouteImport } from './routes/_authenticated/groups'
import { Route as AuthenticatedCheckInIndexRouteImport } from './routes/_authenticated/check-in.index'
import { Route as AuthenticatedChatIndexRouteImport } from './routes/_authenticated/chat.index'
import { Route as AuthenticatedAccountSettingsIndexRouteImport } from './routes/_authenticated/account-settings.index'
import { Route as AuthenticatedCheckInNotesRouteImport } from './routes/_authenticated/check-in.notes'
import { Route as AuthenticatedCheckInCameraRouteImport } from './routes/_authenticated/check-in.camera'
import { Route as AuthenticatedChatGroupIdRouteImport } from './routes/_authenticated/chat.$groupId'
import { Route as AuthenticatedAccountSettingsPasswordRouteImport } from './routes/_authenticated/account-settings.password'
import { Route as AuthenticatedAccountSettingsNotificationsRouteImport } from './routes/_authenticated/account-settings.notifications'
import { Route as AuthenticatedAccountSettingsNameRouteImport } from './routes/_authenticated/account-settings.name'
import { Route as AuthenticatedAccountSettingsEmailRouteImport } from './routes/_authenticated/account-settings.email'
import { Route as ApiPublicHooksMorningRitualReminderRouteImport } from './routes/api/public/hooks/morning-ritual-reminder'
import { Route as ApiPublicHooksAutoMissRouteImport } from './routes/api/public/hooks/auto-miss'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInviteRoute = AuthenticatedInviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGroupsRoute = AuthenticatedGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCheckInIndexRoute =
  AuthenticatedCheckInIndexRouteImport.update({
    id: '/check-in/',
    path: '/check-in/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatIndexRoute = AuthenticatedChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountSettingsIndexRoute =
  AuthenticatedAccountSettingsIndexRouteImport.update({
    id: '/account-settings/',
    path: '/account-settings/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCheckInNotesRoute =
  AuthenticatedCheckInNotesRouteImport.update({
    id: '/check-in/notes',
    path: '/check-in/notes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCheckInCameraRoute =
  AuthenticatedCheckInCameraRouteImport.update({
    id: '/check-in/camera',
    path: '/check-in/camera',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatGroupIdRoute =
  AuthenticatedChatGroupIdRouteImport.update({
    id: '/chat/$groupId',
    path: '/chat/$groupId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccountSettingsPasswordRoute =
  AuthenticatedAccountSettingsPasswordRouteImport.update({
    id: '/account-settings/password',
    path: '/account-settings/password',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccountSettingsNotificationsRoute =
  AuthenticatedAccountSettingsNotificationsRouteImport.update({
    id: '/account-settings/notifications',
    path: '/account-settings/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccountSettingsNameRoute =
  AuthenticatedAccountSettingsNameRouteImport.update({
    id: '/account-settings/name',
    path: '/account-settings/name',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccountSettingsEmailRoute =
  AuthenticatedAccountSettingsEmailRouteImport.update({
    id: '/account-settings/email',
    path: '/account-settings/email',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicHooksMorningRitualReminderRoute =
  ApiPublicHooksMorningRitualReminderRouteImport.update({
    id: '/api/public/hooks/morning-ritual-reminder',
    path: '/api/public/hooks/morning-ritual-reminder',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksAutoMissRoute = ApiPublicHooksAutoMissRouteImport.update({
  id: '/api/public/hooks/auto-miss',
  path: '/api/public/hooks/auto-miss',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/groups': typeof AuthenticatedGroupsRoute
  '/home': typeof AuthenticatedHomeRoute
  '/invite': typeof AuthenticatedInviteRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/account-settings/email': typeof AuthenticatedAccountSettingsEmailRoute
  '/account-settings/name': typeof AuthenticatedAccountSettingsNameRoute
  '/account-settings/notifications': typeof AuthenticatedAccountSettingsNotificationsRoute
  '/account-settings/password': typeof AuthenticatedAccountSettingsPasswordRoute
  '/chat/$groupId': typeof AuthenticatedChatGroupIdRoute
  '/check-in/camera': typeof AuthenticatedCheckInCameraRoute
  '/check-in/notes': typeof AuthenticatedCheckInNotesRoute
  '/account-settings/': typeof AuthenticatedAccountSettingsIndexRoute
  '/chat/': typeof AuthenticatedChatIndexRoute
  '/check-in/': typeof AuthenticatedCheckInIndexRoute
  '/api/public/hooks/auto-miss': typeof ApiPublicHooksAutoMissRoute
  '/api/public/hooks/morning-ritual-reminder': typeof ApiPublicHooksMorningRitualReminderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/groups': typeof AuthenticatedGroupsRoute
  '/home': typeof AuthenticatedHomeRoute
  '/invite': typeof AuthenticatedInviteRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/account-settings/email': typeof AuthenticatedAccountSettingsEmailRoute
  '/account-settings/name': typeof AuthenticatedAccountSettingsNameRoute
  '/account-settings/notifications': typeof AuthenticatedAccountSettingsNotificationsRoute
  '/account-settings/password': typeof AuthenticatedAccountSettingsPasswordRoute
  '/chat/$groupId': typeof AuthenticatedChatGroupIdRoute
  '/check-in/camera': typeof AuthenticatedCheckInCameraRoute
  '/check-in/notes': typeof AuthenticatedCheckInNotesRoute
  '/account-settings': typeof AuthenticatedAccountSettingsIndexRoute
  '/chat': typeof AuthenticatedChatIndexRoute
  '/check-in': typeof AuthenticatedCheckInIndexRoute
  '/api/public/hooks/auto-miss': typeof ApiPublicHooksAutoMissRoute
  '/api/public/hooks/morning-ritual-reminder': typeof ApiPublicHooksMorningRitualReminderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/groups': typeof AuthenticatedGroupsRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/invite': typeof AuthenticatedInviteRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/account-settings/email': typeof AuthenticatedAccountSettingsEmailRoute
  '/_authenticated/account-settings/name': typeof AuthenticatedAccountSettingsNameRoute
  '/_authenticated/account-settings/notifications': typeof AuthenticatedAccountSettingsNotificationsRoute
  '/_authenticated/account-settings/password': typeof AuthenticatedAccountSettingsPasswordRoute
  '/_authenticated/chat/$groupId': typeof AuthenticatedChatGroupIdRoute
  '/_authenticated/check-in/camera': typeof AuthenticatedCheckInCameraRoute
  '/_authenticated/check-in/notes': typeof AuthenticatedCheckInNotesRoute
  '/_authenticated/account-settings/': typeof AuthenticatedAccountSettingsIndexRoute
  '/_authenticated/chat/': typeof AuthenticatedChatIndexRoute
  '/_authenticated/check-in/': typeof AuthenticatedCheckInIndexRoute
  '/api/public/hooks/auto-miss': typeof ApiPublicHooksAutoMissRoute
  '/api/public/hooks/morning-ritual-reminder': typeof ApiPublicHooksMorningRitualReminderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/groups'
    | '/home'
    | '/invite'
    | '/profile'
    | '/account-settings/email'
    | '/account-settings/name'
    | '/account-settings/notifications'
    | '/account-settings/password'
    | '/chat/$groupId'
    | '/check-in/camera'
    | '/check-in/notes'
    | '/account-settings/'
    | '/chat/'
    | '/check-in/'
    | '/api/public/hooks/auto-miss'
    | '/api/public/hooks/morning-ritual-reminder'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/groups'
    | '/home'
    | '/invite'
    | '/profile'
    | '/account-settings/email'
    | '/account-settings/name'
    | '/account-settings/notifications'
    | '/account-settings/password'
    | '/chat/$groupId'
    | '/check-in/camera'
    | '/check-in/notes'
    | '/account-settings'
    | '/chat'
    | '/check-in'
    | '/api/public/hooks/auto-miss'
    | '/api/public/hooks/morning-ritual-reminder'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/_authenticated/groups'
    | '/_authenticated/home'
    | '/_authenticated/invite'
    | '/_authenticated/profile'
    | '/_authenticated/account-settings/email'
    | '/_authenticated/account-settings/name'
    | '/_authenticated/account-settings/notifications'
    | '/_authenticated/account-settings/password'
    | '/_authenticated/chat/$groupId'
    | '/_authenticated/check-in/camera'
    | '/_authenticated/check-in/notes'
    | '/_authenticated/account-settings/'
    | '/_authenticated/chat/'
    | '/_authenticated/check-in/'
    | '/api/public/hooks/auto-miss'
    | '/api/public/hooks/morning-ritual-reminder'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ApiPublicHooksAutoMissRoute: typeof ApiPublicHooksAutoMissRoute
  ApiPublicHooksMorningRitualReminderRoute: typeof ApiPublicHooksMorningRitualReminderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invite': {
      id: '/_authenticated/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof AuthenticatedInviteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/groups': {
      id: '/_authenticated/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof AuthenticatedGroupsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/check-in/': {
      id: '/_authenticated/check-in/'
      path: '/check-in'
      fullPath: '/check-in/'
      preLoaderRoute: typeof AuthenticatedCheckInIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat/': {
      id: '/_authenticated/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof AuthenticatedChatIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account-settings/': {
      id: '/_authenticated/account-settings/'
      path: '/account-settings'
      fullPath: '/account-settings/'
      preLoaderRoute: typeof AuthenticatedAccountSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/check-in/notes': {
      id: '/_authenticated/check-in/notes'
      path: '/check-in/notes'
      fullPath: '/check-in/notes'
      preLoaderRoute: typeof AuthenticatedCheckInNotesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/check-in/camera': {
      id: '/_authenticated/check-in/camera'
      path: '/check-in/camera'
      fullPath: '/check-in/camera'
      preLoaderRoute: typeof AuthenticatedCheckInCameraRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat/$groupId': {
      id: '/_authenticated/chat/$groupId'
      path: '/chat/$groupId'
      fullPath: '/chat/$groupId'
      preLoaderRoute: typeof AuthenticatedChatGroupIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account-settings/password': {
      id: '/_authenticated/account-settings/password'
      path: '/account-settings/password'
      fullPath: '/account-settings/password'
      preLoaderRoute: typeof AuthenticatedAccountSettingsPasswordRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account-settings/notifications': {
      id: '/_authenticated/account-settings/notifications'
      path: '/account-settings/notifications'
      fullPath: '/account-settings/notifications'
      preLoaderRoute: typeof AuthenticatedAccountSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account-settings/name': {
      id: '/_authenticated/account-settings/name'
      path: '/account-settings/name'
      fullPath: '/account-settings/name'
      preLoaderRoute: typeof AuthenticatedAccountSettingsNameRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account-settings/email': {
      id: '/_authenticated/account-settings/email'
      path: '/account-settings/email'
      fullPath: '/account-settings/email'
      preLoaderRoute: typeof AuthenticatedAccountSettingsEmailRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/hooks/morning-ritual-reminder': {
      id: '/api/public/hooks/morning-ritual-reminder'
      path: '/api/public/hooks/morning-ritual-reminder'
      fullPath: '/api/public/hooks/morning-ritual-reminder'
      preLoaderRoute: typeof ApiPublicHooksMorningRitualReminderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/auto-miss': {
      id: '/api/public/hooks/auto-miss'
      path: '/api/public/hooks/auto-miss'
      fullPath: '/api/public/hooks/auto-miss'
      preLoaderRoute: typeof ApiPublicHooksAutoMissRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedGroupsRoute: typeof AuthenticatedGroupsRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedInviteRoute: typeof AuthenticatedInviteRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedAccountSettingsEmailRoute: typeof AuthenticatedAccountSettingsEmailRoute
  AuthenticatedAccountSettingsNameRoute: typeof AuthenticatedAccountSettingsNameRoute
  AuthenticatedAccountSettingsNotificationsRoute: typeof AuthenticatedAccountSettingsNotificationsRoute
  AuthenticatedAccountSettingsPasswordRoute: typeof AuthenticatedAccountSettingsPasswordRoute
  AuthenticatedChatGroupIdRoute: typeof AuthenticatedChatGroupIdRoute
  AuthenticatedCheckInCameraRoute: typeof AuthenticatedCheckInCameraRoute
  AuthenticatedCheckInNotesRoute: typeof AuthenticatedCheckInNotesRoute
  AuthenticatedAccountSettingsIndexRoute: typeof AuthenticatedAccountSettingsIndexRoute
  AuthenticatedChatIndexRoute: typeof AuthenticatedChatIndexRoute
  AuthenticatedCheckInIndexRoute: typeof AuthenticatedCheckInIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedGroupsRoute: AuthenticatedGroupsRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedInviteRoute: AuthenticatedInviteRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedAccountSettingsEmailRoute:
    AuthenticatedAccountSettingsEmailRoute,
  AuthenticatedAccountSettingsNameRoute: AuthenticatedAccountSettingsNameRoute,
  AuthenticatedAccountSettingsNotificationsRoute:
    AuthenticatedAccountSettingsNotificationsRoute,
  AuthenticatedAccountSettingsPasswordRoute:
    AuthenticatedAccountSettingsPasswordRoute,
  AuthenticatedChatGroupIdRoute: AuthenticatedChatGroupIdRoute,
  AuthenticatedCheckInCameraRoute: AuthenticatedCheckInCameraRoute,
  AuthenticatedCheckInNotesRoute: AuthenticatedCheckInNotesRoute,
  AuthenticatedAccountSettingsIndexRoute:
    AuthenticatedAccountSettingsIndexRoute,
  AuthenticatedChatIndexRoute: AuthenticatedChatIndexRoute,
  AuthenticatedCheckInIndexRoute: AuthenticatedCheckInIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ApiPublicHooksAutoMissRoute: ApiPublicHooksAutoMissRoute,
  ApiPublicHooksMorningRitualReminderRoute:
    ApiPublicHooksMorningRitualReminderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
