/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedInviteRouteImport } from './routes/_authenticated/invite'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedGroupsRouteImport } from './routes/_authenticated/groups'
import { Route as AuthenticatedCheckInIndexRouteImport } from './routes/_authenticated/check-in.index'
import { Route as AuthenticatedChatIndexRouteImport } from './routes/_authenticated/chat.index'
import { Route as AuthenticatedCheckInNotesRouteImport } from './routes/_authenticated/check-in.notes'
import { Route as AuthenticatedCheckInCameraRouteImport } from './routes/_authenticated/check-in.camera'
import { Route as AuthenticatedChatGroupIdRouteImport } from './routes/_authenticated/chat.$groupId'
import { Route as ApiPublicHooksAutoMissRouteImport } from './routes/api/public/hooks/auto-miss'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInviteRoute = AuthenticatedInviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGroupsRoute = AuthenticatedGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCheckInIndexRoute =
  AuthenticatedCheckInIndexRouteImport.update({
    id: '/check-in/',
    path: '/check-in/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatIndexRoute = AuthenticatedChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCheckInNotesRoute =
  AuthenticatedCheckInNotesRouteImport.update({
    id: '/check-in/notes',
    path: '/check-in/notes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCheckInCameraRoute =
  AuthenticatedCheckInCameraRouteImport.update({
    id: '/check-in/camera',
    path: '/check-in/camera',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatGroupIdRoute =
  AuthenticatedChatGroupIdRouteImport.update({
    id: '/chat/$groupId',
    path: '/chat/$groupId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicHooksAutoMissRoute = ApiPublicHooksAutoMissRouteImport.update({
  id: '/api/public/hooks/auto-miss',
  path: '/api/public/hooks/auto-miss',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/groups': typeof AuthenticatedGroupsRoute
  '/home': typeof AuthenticatedHomeRoute
  '/invite': typeof AuthenticatedInviteRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/chat/$groupId': typeof AuthenticatedChatGroupIdRoute
  '/check-in/camera': typeof AuthenticatedCheckInCameraRoute
  '/check-in/notes': typeof AuthenticatedCheckInNotesRoute
  '/chat/': typeof AuthenticatedChatIndexRoute
  '/check-in/': typeof AuthenticatedCheckInIndexRoute
  '/api/public/hooks/auto-miss': typeof ApiPublicHooksAutoMissRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/groups': typeof AuthenticatedGroupsRoute
  '/home': typeof AuthenticatedHomeRoute
  '/invite': typeof AuthenticatedInviteRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/chat/$groupId': typeof AuthenticatedChatGroupIdRoute
  '/check-in/camera': typeof AuthenticatedCheckInCameraRoute
  '/check-in/notes': typeof AuthenticatedCheckInNotesRoute
  '/chat': typeof AuthenticatedChatIndexRoute
  '/check-in': typeof AuthenticatedCheckInIndexRoute
  '/api/public/hooks/auto-miss': typeof ApiPublicHooksAutoMissRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/groups': typeof AuthenticatedGroupsRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/invite': typeof AuthenticatedInviteRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/chat/$groupId': typeof AuthenticatedChatGroupIdRoute
  '/_authenticated/check-in/camera': typeof AuthenticatedCheckInCameraRoute
  '/_authenticated/check-in/notes': typeof AuthenticatedCheckInNotesRoute
  '/_authenticated/chat/': typeof AuthenticatedChatIndexRoute
  '/_authenticated/check-in/': typeof AuthenticatedCheckInIndexRoute
  '/api/public/hooks/auto-miss': typeof ApiPublicHooksAutoMissRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/groups'
    | '/home'
    | '/invite'
    | '/profile'
    | '/chat/$groupId'
    | '/check-in/camera'
    | '/check-in/notes'
    | '/chat/'
    | '/check-in/'
    | '/api/public/hooks/auto-miss'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/groups'
    | '/home'
    | '/invite'
    | '/profile'
    | '/chat/$groupId'
    | '/check-in/camera'
    | '/check-in/notes'
    | '/chat'
    | '/check-in'
    | '/api/public/hooks/auto-miss'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/groups'
    | '/_authenticated/home'
    | '/_authenticated/invite'
    | '/_authenticated/profile'
    | '/_authenticated/chat/$groupId'
    | '/_authenticated/check-in/camera'
    | '/_authenticated/check-in/notes'
    | '/_authenticated/chat/'
    | '/_authenticated/check-in/'
    | '/api/public/hooks/auto-miss'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ApiPublicHooksAutoMissRoute: typeof ApiPublicHooksAutoMissRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invite': {
      id: '/_authenticated/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof AuthenticatedInviteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/groups': {
      id: '/_authenticated/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof AuthenticatedGroupsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/check-in/': {
      id: '/_authenticated/check-in/'
      path: '/check-in'
      fullPath: '/check-in/'
      preLoaderRoute: typeof AuthenticatedCheckInIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat/': {
      id: '/_authenticated/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof AuthenticatedChatIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/check-in/notes': {
      id: '/_authenticated/check-in/notes'
      path: '/check-in/notes'
      fullPath: '/check-in/notes'
      preLoaderRoute: typeof AuthenticatedCheckInNotesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/check-in/camera': {
      id: '/_authenticated/check-in/camera'
      path: '/check-in/camera'
      fullPath: '/check-in/camera'
      preLoaderRoute: typeof AuthenticatedCheckInCameraRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat/$groupId': {
      id: '/_authenticated/chat/$groupId'
      path: '/chat/$groupId'
      fullPath: '/chat/$groupId'
      preLoaderRoute: typeof AuthenticatedChatGroupIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/hooks/auto-miss': {
      id: '/api/public/hooks/auto-miss'
      path: '/api/public/hooks/auto-miss'
      fullPath: '/api/public/hooks/auto-miss'
      preLoaderRoute: typeof ApiPublicHooksAutoMissRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedGroupsRoute: typeof AuthenticatedGroupsRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedInviteRoute: typeof AuthenticatedInviteRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedChatGroupIdRoute: typeof AuthenticatedChatGroupIdRoute
  AuthenticatedCheckInCameraRoute: typeof AuthenticatedCheckInCameraRoute
  AuthenticatedCheckInNotesRoute: typeof AuthenticatedCheckInNotesRoute
  AuthenticatedChatIndexRoute: typeof AuthenticatedChatIndexRoute
  AuthenticatedCheckInIndexRoute: typeof AuthenticatedCheckInIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedGroupsRoute: AuthenticatedGroupsRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedInviteRoute: AuthenticatedInviteRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedChatGroupIdRoute: AuthenticatedChatGroupIdRoute,
  AuthenticatedCheckInCameraRoute: AuthenticatedCheckInCameraRoute,
  AuthenticatedCheckInNotesRoute: AuthenticatedCheckInNotesRoute,
  AuthenticatedChatIndexRoute: AuthenticatedChatIndexRoute,
  AuthenticatedCheckInIndexRoute: AuthenticatedCheckInIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ApiPublicHooksAutoMissRoute: ApiPublicHooksAutoMissRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
